"""updated score table fields

Revision ID: 370aed73f00c
Revises: 5c05af59b552
Create Date: 2022-05-22 17:25:19.459422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370aed73f00c'
down_revision = '5c05af59b552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('onlineGamesPlayed', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('onlineAverageGuesses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'onlineAverageGuesses')
    op.drop_column('score', 'onlineGamesPlayed')
    # ### end Alembic commands ###
