"""empty message

Revision ID: 5c05af59b552
Revises: 927c38be824e
Create Date: 2022-05-22 15:46:40.997695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c05af59b552'
down_revision = '927c38be824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'onlineWinPercentage')
    op.drop_column('score', 'onlineGamesPlayed')
    op.drop_column('score', 'score')
    op.drop_column('score', 'onlineAverageGuesses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('onlineAverageGuesses', sa.INTEGER(), nullable=True))
    op.add_column('score', sa.Column('score', sa.INTEGER(), nullable=True))
    op.add_column('score', sa.Column('onlineGamesPlayed', sa.INTEGER(), nullable=True))
    op.add_column('score', sa.Column('onlineWinPercentage', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
