"""stats  table

Revision ID: 6e02f882df7a
Revises: d351a18fa368
Create Date: 2022-05-23 01:47:45.628348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e02f882df7a'
down_revision = 'd351a18fa368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('onlineGamesWon', sa.Integer(), nullable=True),
    sa.Column('onlineGamesPlayed', sa.Integer(), nullable=True),
    sa.Column('onlineAvgGuesses', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
