"""score table

Revision ID: 927c38be824e
Revises: 61e69bca14fb
Create Date: 2022-05-22 11:41:12.153145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927c38be824e'
down_revision = '61e69bca14fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('onlineGamesPlayed', sa.Integer(), nullable=True),
    sa.Column('onlineGamesWon', sa.Integer(), nullable=True),
    sa.Column('onlineAverageGuesses', sa.Integer(), nullable=True),
    sa.Column('onlineWinPercentage', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score')
    # ### end Alembic commands ###
